### PR TITLE
Allows entities to be extended by a custom parent class

### PR DESCRIPTION
**Pull request by Prometee**
This PR is allowing to extends the 2 Doctrine entities available.

- [x] Swicth to XML mapping (not required but it will if this plugin wants to support PHP 8.1 one day).
- [x] Make properties `protected` instead of `private`.
- [x] Switch from Doctrine Table to MappedSuperClass to allow overrides.
- [ ] Add overrided entities to the flex recipe to test the override ?

Note: I saw some entity properties are nullable but they aren't when you look at the database schema definition.

### CODE REVIEW

**Review by jacquesbh — APPROVED** [review]
LGTM

**Comment by jacquesbh** [comment]
@Prometee The null properties are correct. We use them to avoid issues with Doctrine, since you can't access a property which hasn't been set in the first place. `null` becomes then the default value. But everything in the code disallows those values to be null elsewhere out of the PHP class.

**Review by delyriand — APPROVED** [review]
LGTM

And I think we will leave for later the last point of the TODO concerning the entity override test.

**Review by lanfisis — APPROVED** [review]

**Comment by Prometee** [comment]
@lanfisis or @delyriand Can you run one last time the build to see if everything is ok ?

**Comment by lanfisis** [comment]
> @lanfisis or @delyriand Can you run one last time the build to see if everything is ok ?

Done, it's running

**Comment by maximehuran** [comment]
Thank you @Prometee the doctrine is not up to date, if I run a `diff` : 

```
        $this->addSql('ALTER TABLE mbiz_alert_message CHANGE enabled enabled TINYINT(1) DEFAULT true NOT NULL, CHANGE customers_only customers_only TINYINT(1) DEFAULT false NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE template_html template_html VARCHAR(255) DEFAULT NULL');
```

It seems the default value is `true` instead of `1` and `false` instead of `0`.

**Comment by Prometee** [comment]
@maximehuran that's what I saw to, I just fixed it 😉

**Comment by maximehuran** [comment]
It stills have

```
CHANGE created_at created_at DATETIME NOT NULL, CHANGE template_html template_html VARCHAR(255) DEFAULT NULL
```

**Comment by Prometee** [comment]
@maximehuran my bad I did not scroll right 😅
I fixed all types it should be good now, you can re-run the build now.

**Review by maximehuran — APPROVED** [review]

**Comment by maximehuran** [comment]
Thank you very much @Prometee 🫶

**Pull request merged**
